Json log parsing
appuio/component-openshift4-logging pull request #16
Opened 2021-08-20 10:18 UTC by DebakelOrakel

## Checklist

- [x] Keep pull requests small so they can be easily reviewed.
- [x] Update the documentation.
- [x] Categorize the PR by setting a good title and adding one of the labels:
      `bug`, `enhancement`, `documentation`, `change`, `breaking`, `dependency`
      as they show up in the changelog
- [ ] Link this PR to related issues.

2021-08-20 10:20 UTC, DebakelOrakel commented
Depends on #14

2021-08-20 12:00 UTC, simu commented
Please finish and merge #14 first and rebase this afterwards, it's unclear which changes belong to this PR and which belong to #14 currently.

2021-08-20 12:08 UTC, simu approved these changes
Implementation looks good.

Does this also affect logs which are ingested into the default cluster-logging Elasticsearch? That's not very clear from the documentation.

PS: why are there 15 commits in this PR?

2021-08-20 12:08 UTC, simu commented on docs/modules/ROOT/pages/references/parameters.adoc
> +If `json.enabled` is set to `true` the logging stack attempts to parse log messages to the json format.
```suggestion
If `json.enabled` is set to `true` the logging stack attempts to parse log messages to the JSON format.
```

2021-08-20 12:08 UTC, simu commented on docs/modules/ROOT/pages/references/parameters.adoc
> +<1> By default json parsing is disabled.
```suggestion
<1> By default JSON parsing is disabled.
```

2021-08-20 12:16 UTC, DebakelOrakel commented
> Does this also affect logs which are ingested into the default cluster-logging Elasticsearch? That's not very clear from the documentation.
It does affect all logs. It works like this:
* it tries to parse the `message` field to json and saves it in a new field `structured`
* if the pod (depending on configuration) has a label `logformat=apache` it creates a new index `app-apache-xxxxx` where the structured fields are indexed and searchable
* if it cant parse the `message` field no `structured` field is created
 
> PS: why are there 15 commits in this PR?
I was wondering that either, probably bc i checked out from the other branch...

2021-08-20 12:45 UTC, simu commented
> > PS: why are there 15 commits in this PR?
> I was wondering that either, probably bc i checked out from the other branch...

Looking at the commits in more detail, it's probably because you used GitHub's "Update Branch" which just merges master into the feature branch instead of rebasing the feature branch on the latest master.

2021-08-23 07:41 UTC, corvus-ch requested changes
LGTM except for the git history. Please rebase.

2021-08-23 07:41 UTC, corvus-ch commented on docs/modules/ROOT/pages/references/parameters.adoc
> +See the https://docs.openshift.com/container-platform/4.7/logging/cluster-logging-enabling-json-logging.html#cluster-logging-configuration-of-json-log-data-for-default-elasticsearch_cluster-logging-e
```suggestion
See the https://docs.openshift.com/container-platform/4.8/logging/cluster-logging-enabling-json-logging.html#cluster-logging-configuration-of-json-log-data-for-default-elasticsearch_cluster-logging-enabling-json-logging[OpenShift docs] for a detailed explanation.
```

2021-08-23 08:25 UTC, DebakelOrakel commented
WTF... git, are you mad?

2021-08-23 08:26 UTC, DebakelOrakel commented on docs/modules/ROOT/pages/references/parameters.adoc
> +See the https://docs.openshift.com/container-platform/4.7/logging/cluster-logging-enabling-json-logging.html#cluster-logging-configuration-of-json-log-data-for-default-elasticsearch_cluster-logging-e
Ah, that should be latest.

2021-08-23 14:20 UTC, corvus-ch approved these changes

2021-08-23 15:08 UTC, merged